export enum BackgroundEnum {
  Card1Background1 = 'assets/img/card1Background1.png',
  Card1Background2 = 'assets/img/card1Background2.png',
  Card2Background1 = 'assets/img/card2Background1.png',
  Card2Background2 = 'assets/img/card2Background2.png',
  Card2Background3 = 'assets/img/card2Background3.png',
  Card3Background1 = 'assets/img/card3Background1.png',
  Card3Background2 = 'assets/img/card3Background2.png',
  Card4Background1 = 'assets/img/card4Background1.png',
  Card4Background2 = 'assets/img/card4Background2.png',
  Card5Background1 = 'assets/img/card5Background1.png',
  Card5Background2 = 'assets/img/card5Background2.png',
  Card6Background1 = 'assets/img/card6Background1.png',
  Card6Background2 = 'assets/img/card6Background2.png',

  TradeRuWhite = 'assets/img/trade_ru_white.png',
  TradeRuWhiteTpsl = 'assets/img/trade_ru_white_tpsl.png',
  TradeRuBlack = 'assets/img/trade_ru_black.png',
  TradeRuBlackTpsl = 'assets/img/trade_ru_black_tpsl.png',
  TradeEnBlack = 'assets/img/trade_en_black.png',
  TradeEnWhite = 'assets/img/trade_en_white.png',
  TradeEnBlackTpsl = 'assets/img/trade_en_black_tpsl.png',
  TradeEnWhiteTpsl = 'assets/img/trade_en_white_tpsl.png',

  TpslRuWhite = 'assets/img/tpslRuWhite.png',
  TpslEnWhite = 'assets/img/tpslEnWhite.png',
  TpslRuBlack = 'assets/img/tpslRuBlack.png',
  TpslEnBlack = 'assets/img/tpslEnBlack.png',
  MexcCard1RuBlack = 'assets/img/mexc1-black-ru-blank.png',
  MexcCard1EnBlack = 'assets/img/mexc1-black-en-blank.png',
  MexCard2Ru1 = 'assets/img/mexc2-background1-ru.png',
  MexCard2Ru2 = 'assets/img/mexc2-background2-ru.png',
  MexCard2Ru3 = 'assets/img/mexc2-background3-ru.png',
  MexCard2Ru4 = 'assets/img/mexc2-background4-ru.png',
  MexCard2Ru5 = 'assets/img/mexc2-background5-ru.png',
  MexCard2En1 = 'assets/img/mexc2-background1-en.png',
  MexCard2En2 = 'assets/img/mexc2-background2-en.png',
  MexCard2En3 = 'assets/img/mexc2-background3-en.png',
  MexCard2En4 = 'assets/img/mexc2-background4-en.png',
  MexCard2En5 = 'assets/img/mexc2-background5-en.png',
}
