export enum BackgroundEnum {
  Card1Background1 = 'assets/img/card1Background1.png',
  Card1Background2 = 'assets/img/card1Background2.png',
  Card2Background1 = 'assets/img/card2Background1.png',
  Card2Background2 = 'assets/img/card2Background2.png',
  Card2Background3 = 'assets/img/card2Background3.png',
  Card3Background1 = 'assets/img/card3Background1.png',
  Card3Background2 = 'assets/img/card3Background2.png',
  Card4Background1 = 'assets/img/card4Background1.png',
  Card4Background2 = 'assets/img/card4Background2.png',
  Card5Background1 = 'assets/img/card5Background1.png',
  Card5Background2 = 'assets/img/card5Background2.png',
  Card6Background1 = 'assets/img/card6Background1.png',
  Card6Background2 = 'assets/img/card6Background2.png',
  TpslRuWhite = 'assets/img/tpslRuWhite.png',
  TpslEnWhite = 'assets/img/tpslEnWhite.png',
  TpslRuBlack = 'assets/img/tpslRuBlack.png',
  TpslEnBlack = 'assets/img/tpslEnBlack.png',
  MexcCard1RuBlack = 'assets/img/mexc1-black-ru-blank.png',
  MexcCard1EnBlack = 'assets/img/mexc1-black-en-blank.png',
}
